### ISSUE TITLE
Package is missing cleaned datasets.

### ISSUE THREAD

**Issue by OlivierBinette** [resteorts/cora#1]
The package currently does not work as advertised. It seems that the computed datasets are not on the repo. The data cleaning scripts currently don't run.

**Comment by resteorts** [comment]
They should all be in here and run properly. Would you mind testing them out and letting me know if you find an issue?

https://github.com/cleanzr/RLdata

On Jul 21, 2020, at 3:35 PM, Olivier <notifications@github.com> wrote:



The package currently does not work as advertised. It seems that the computed datasets are not on the repo. The data cleaning scripts currently don't run.

**Comment by OlivierBinette** [comment]
Everything checks out on resteorts/RLdata. I submitted a pull request incorporating the Cora data here.
